clean up python app

diff --git a/python/run b/python/run
--- a/python/run
+++ b/python/run
@@ -5,8 +5,33 @@
 # Or, run with a parameter service name (from docker-compose) to restart just that service
 # `./run meminator`
 
-set -x # print what you run
+if ! docker compose up --build -d "$@"; then
+  echo ""
+  echo "Failed to build or start services!"
+  exit 1
+fi
 
-docker compose up --build -d $*
+# Check if running in GitHub Codespaces
+if [ -n "$CODESPACES" ]; then
+  echo "Running in GitHub Codespaces."
 
-echo "http://localhost:8080"
+  APP_PORT=10114
+
+  URL="https://${CODESPACE_NAME}-${APP_PORT}.app.github.dev"
+
+# Check if running in Gitpod
+elif [ -n "$GITPOD_INSTANCE_ID" ]; then
+  echo "Running in Gitpod."
+
+  # Get the workspace url
+  URL=$(gp url 10114)
+
+else
+  # Default to local environment
+  echo "Running locally."
+
+  URL="http://localhost:10114/"
+
+fi
+
+echo "Meminator running on port 10114 at: $URL"
